repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-added-large-files
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
# -   repo: https://github.com/astral-sh/ruff-pre-commit
#     # Ruff version.
#     rev: v0.4.4
#     hooks:
#     # Run the linter.
#     -   id: ruff
#         args: [ --fix ]
#     # Run the formatter.
#     -   id: ruff-format
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest
        language: system
        types: [python]
        stages: [commit]
        pass_filenames: false
        always_run: true

    -   id: ruff-linter-with-isort
        name: ruff lint with isort
        entry: ruff check --select I --fix
        language: system
        types: [python]
        stages: [commit]

    -   id: ruff-format
        name: ruff format
        entry: ruff format
        language: system
        types: [python]
        stages: [commit]
