site_name: Launchd Me
repo_url: https://github.com/chrisbillows/launchd-me
repo_name: launchd-me
theme:
  name: material
  logo: img/128px-Cartoon_space_rocket.png
  favicon: img/favicon.ico
  language: en
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - toc.follow
    - content.tooltips
    - content.code.copy

markdown_extensions:
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
- search
- mkdocstrings:
      handlers:
        python:
          docstring_style: "numpy"
          options:
            # docstring_section_style: table
            # filters: ["!^_"]
            heading_level: 2
            # inherited_members: true
            merge_init_into_class: false
            parameter_headings: true
            separate_signature: true
            show_root_heading: true
            show_root_full_path: true
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            # signature_crossrefs: true
            summary: true

nav:
  - Launchd Me: home.md
  - What is launchd: what_is_launchd.md
  - User Guide: user_guide.md
  - Maintainer: maintainer.md
  - FAQs: faqs.md
  - API: api.md
