name: Python Application Tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install the package
      run: pip install .

    - name: Run ruff
      run: ruff check --select I --fix

    - name: Run ruff format
      run: ruff format

    - name: Run pytest
      run: pytest

    - name: Run ldm --help
      run: ldm --help
